// 주요 코스피/코스닥 종목 한글명 -> 티커 매핑 (한글 검색 지원용)
export interface KrStock {
  symbol: string;
  name: string;
  market: "KOSPI" | "KOSDAQ";
}

export const KR_STOCKS: KrStock[] = [
  { symbol: "005930.KS", name: "삼성전자", market: "KOSPI" },
  { symbol: "000660.KS", name: "SK하이닉스", market: "KOSPI" },
  { symbol: "373220.KS", name: "LG에너지솔루션", market: "KOSPI" },
  { symbol: "207940.KS", name: "삼성바이오로직스", market: "KOSPI" },
  { symbol: "005380.KS", name: "현대차", market: "KOSPI" },
  { symbol: "000270.KS", name: "기아", market: "KOSPI" },
  { symbol: "068270.KS", name: "셀트리온", market: "KOSPI" },
  { symbol: "035420.KS", name: "NAVER", market: "KOSPI" },
  { symbol: "051910.KS", name: "LG화학", market: "KOSPI" },
  { symbol: "006400.KS", name: "삼성SDI", market: "KOSPI" },
  { symbol: "035720.KS", name: "카카오", market: "KOSPI" },
  { symbol: "105560.KS", name: "KB금융", market: "KOSPI" },
  { symbol: "012330.KS", name: "현대모비스", market: "KOSPI" },
  { symbol: "055550.KS", name: "신한지주", market: "KOSPI" },
  { symbol: "028260.KS", name: "삼성물산", market: "KOSPI" },
  { symbol: "066570.KS", name: "LG전자", market: "KOSPI" },
  { symbol: "003670.KS", name: "포스코퓨처엠", market: "KOSPI" },
  { symbol: "005490.KS", name: "POSCO홀딩스", market: "KOSPI" },
  { symbol: "032830.KS", name: "삼성생명", market: "KOSPI" },
  { symbol: "003550.KS", name: "LG", market: "KOSPI" },
  { symbol: "009150.KS", name: "삼성전기", market: "KOSPI" },
  { symbol: "017670.KS", name: "SK텔레콤", market: "KOSPI" },
  { symbol: "030200.KS", name: "KT", market: "KOSPI" },
  { symbol: "086790.KS", name: "하나금융지주", market: "KOSPI" },
  { symbol: "316140.KS", name: "우리금융지주", market: "KOSPI" },
  { symbol: "138040.KS", name: "메리츠금융지주", market: "KOSPI" },
  { symbol: "033780.KS", name: "KT&G", market: "KOSPI" },
  { symbol: "015760.KS", name: "한국전력", market: "KOSPI" },
  { symbol: "034730.KS", name: "SK", market: "KOSPI" },
  { symbol: "018260.KS", name: "삼성에스디에스", market: "KOSPI" },
  { symbol: "010130.KS", name: "고려아연", market: "KOSPI" },
  { symbol: "011200.KS", name: "HMM", market: "KOSPI" },
  { symbol: "024110.KS", name: "기업은행", market: "KOSPI" },
  { symbol: "047050.KS", name: "포스코인터내셔널", market: "KOSPI" },
  { symbol: "096770.KS", name: "SK이노베이션", market: "KOSPI" },
  { symbol: "010950.KS", name: "S-Oil", market: "KOSPI" },
  { symbol: "316140.KS", name: "우리금융지주", market: "KOSPI" },
  { symbol: "034220.KS", name: "LG디스플레이", market: "KOSPI" },
  { symbol: "012450.KS", name: "한화에어로스페이스", market: "KOSPI" },
  { symbol: "267260.KS", name: "HD현대일렉트릭", market: "KOSPI" },
  { symbol: "009540.KS", name: "HD한국조선해양", market: "KOSPI" },
  { symbol: "010140.KS", name: "삼성중공업", market: "KOSPI" },
  { symbol: "042660.KS", name: "한화오션", market: "KOSPI" },
  { symbol: "086280.KS", name: "현대글로비스", market: "KOSPI" },
  { symbol: "011170.KS", name: "롯데케미칼", market: "KOSPI" },
  { symbol: "352820.KS", name: "하이브", market: "KOSPI" },
  { symbol: "035250.KS", name: "강원랜드", market: "KOSPI" },
  { symbol: "377300.KS", name: "카카오페이", market: "KOSPI" },
  { symbol: "323410.KS", name: "카카오뱅크", market: "KOSPI" },
  { symbol: "259960.KS", name: "크래프톤", market: "KOSPI" },
  { symbol: "036570.KS", name: "엔씨소프트", market: "KOSPI" },
  { symbol: "251270.KS", name: "넷마블", market: "KOSPI" },
  { symbol: "302440.KS", name: "SK바이오사이언스", market: "KOSPI" },
  { symbol: "326030.KS", name: "SK바이오팜", market: "KOSPI" },
  { symbol: "128940.KS", name: "한미약품", market: "KOSPI" },
  { symbol: "000810.KS", name: "삼성화재", market: "KOSPI" },
  { symbol: "021240.KS", name: "코웨이", market: "KOSPI" },
  { symbol: "088350.KS", name: "한화생명", market: "KOSPI" },
  { symbol: "006800.KS", name: "미래에셋증권", market: "KOSPI" },
  { symbol: "016360.KS", name: "삼성증권", market: "KOSPI" },
  { symbol: "071050.KS", name: "한국금융지주", market: "KOSPI" },
  { symbol: "180640.KS", name: "한진칼", market: "KOSPI" },
  { symbol: "003490.KS", name: "대한항공", market: "KOSPI" },
  { symbol: "029780.KS", name: "삼성카드", market: "KOSPI" },
  { symbol: "161390.KS", name: "한국타이어앤테크놀로지", market: "KOSPI" },
  { symbol: "004020.KS", name: "현대제철", market: "KOSPI" },
  { symbol: "298040.KS", name: "효성중공업", market: "KOSPI" },
  { symbol: "047810.KS", name: "한국항공우주", market: "KOSPI" },
  { symbol: "010620.KS", name: "현대미포조선", market: "KOSPI" },
  { symbol: "138930.KS", name: "BNK금융지주", market: "KOSPI" },
  { symbol: "139480.KS", name: "이마트", market: "KOSPI" },
  { symbol: "097950.KS", name: "CJ제일제당", market: "KOSPI" },
  { symbol: "271560.KS", name: "오리온", market: "KOSPI" },
  { symbol: "090430.KS", name: "아모레퍼시픽", market: "KOSPI" },
  { symbol: "051900.KS", name: "LG생활건강", market: "KOSPI" },
  { symbol: "247540.KQ", name: "에코프로비엠", market: "KOSDAQ" },
  { symbol: "086520.KQ", name: "에코프로", market: "KOSDAQ" },
  { symbol: "091990.KQ", name: "셀트리온헬스케어", market: "KOSDAQ" },
  { symbol: "196170.KQ", name: "알테오젠", market: "KOSDAQ" },
  { symbol: "066970.KQ", name: "엘앤에프", market: "KOSDAQ" },
  { symbol: "028300.KQ", name: "HLB", market: "KOSDAQ" },
  { symbol: "293490.KQ", name: "카카오게임즈", market: "KOSDAQ" },
  { symbol: "041510.KQ", name: "에스엠", market: "KOSDAQ" },
  { symbol: "035900.KQ", name: "JYP Ent.", market: "KOSDAQ" },
  { symbol: "122870.KQ", name: "와이지엔터테인먼트", market: "KOSDAQ" },
  { symbol: "112040.KQ", name: "위메이드", market: "KOSDAQ" },
  { symbol: "240810.KQ", name: "원익IPS", market: "KOSDAQ" },
  { symbol: "058470.KQ", name: "리노공업", market: "KOSDAQ" },
  { symbol: "095340.KQ", name: "ISC", market: "KOSDAQ" },
  { symbol: "214150.KQ", name: "클래시스", market: "KOSDAQ" },
  { symbol: "145020.KQ", name: "휴젤", market: "KOSDAQ" },
  { symbol: "022100.KQ", name: "포스코DX", market: "KOSDAQ" },
];

/**
 * 검색어로 한국 종목 검색 (한글/영문 부분일치)
 */
export function searchKrStocks(query: string, limit = 5): KrStock[] {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  return KR_STOCKS.filter(
    (s) => s.name.toLowerCase().includes(q) || s.symbol.toLowerCase().includes(q)
  ).slice(0, limit);
}
